name: Testing web application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Get dependencies and run all tests
      run: |
        go mod tidy
        make test_all
