name: Tegridy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Get dependencies and run individual tests
      run: |
        go mod tidy
        make test_app_health
        make test_get_products
        make test_retrieve_product
        make test_create_product
        make test_toy_database

    - name: Run all tests and coverage
      run: |
        make test_app
        make test_coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3